[package]
name = "lucifer1004/future-machine"
version = "0.1.2"
description = "A simple encoder/decoder"
license = "MIT"
readme = "README.md"
repository = "https://github.com/lucifer1004/geekgame/2021/future-machine"

[[module]]
name = "future-machine"
source = "target/wasm32-wasi/release/future_machine.wasm"
abi = "wasi"

[[command]]
name = "future-machine"
module = "future-machine"
